name: Sync Withings to Garmin

on:
  workflow_dispatch: # Ermöglicht den manuellen Startknopf
  schedule:
    - cron: '0 */6 * * *' # Läuft ab jetzt automatisch alle 6 Stunden

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-python: '3.10'

      - name: Install dependencies
        run: |
          pip install withings-sync

      - name: Run Sync
        env:
          GARMIN_USERNAME: ${{ secrets.GARMIN_USERNAME }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          WITHINGS_CLIENT_ID: ${{ secrets.WITHINGS_CLIENT_ID }}
          WITHINGS_CLIENT_SECRET: ${{ secrets.WITHINGS_CLIENT_SECRET }}
        run: |
          withings-sync
